### ISSUE TITLE
Interval Algorithm

### ISSUE THREAD

**Issue by johnlinahan** [Pitt-CSC/EventScheduler#3]
Implement an interval algorithm to find the time range with the least overlapping classes.

**Comment by RitwikGupta** [comment]
Damn it, I was just about to work on this

**Comment by johnlinahan** [comment]
Wait, can we actually work on this?

**Comment by RitwikGupta** [comment]
Yeah, let's do it. I can't imagine it would be too crazy to come up with something simple

**Comment by johnlinahan** [comment]
@azharichenko I don't have push access, this is an OUTRAGE.

**Comment by RitwikGupta** [comment]
I sent you an invite to be a member

**Comment by azharichenko** [comment]
@johnlinahan I have dubbed you Sir Linny, Admin of the Event Scheduler

**Comment by johnlinahan** [comment]
Status update?

**Comment by azharichenko** [comment]
Lol, i send you an invite again to be dubbed  Sir Linny, Admin of the Event Scheduler

**Comment by johnlinahan** [comment]
wontfix

**Comment by azharichenko** [comment]
😂
